fixes

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,6 +1,9 @@
 #!/bin/sh
 
-. "/etc/sin/sv/$2" || die "$0: unknown service '$1'"
+. /etc/sin/lib
+if [ -n "$2" ]; then 
+    . "/etc/sin/sv/$2" || die "$0: unknown service '$1'"
+fi
 
 usage() {
     cat << .
@@ -17,16 +20,16 @@ Options:
 
 case $1 in
     --start|-s)
-        start || die "$0: failed to start '$1'"
+        start || die "$0: failed to start '$2'"
         ;;
     --kill|--stop|-k)
-        stop || die "$0: failed to stop '$1'"
+        stop || die "$0: failed to stop '$2'"
         ;;
     --restart|-r)
-        if ! type restart | grep -q function; then
-            ( stop && start ) || die "$0: failed to restart '$1'"
+        if ! type restart >/dev/null 2>&1 | grep -q function; then
+            ( stop && start ) || die "$0: failed to restart '$2'"
         else
-            restart || die "$0: failed to restart '$1'"
+            restart || die "$0: failed to restart '$2'"
         fi
         ;;
     --version|-V)
